# npm-check-updates configuration used by yarn deps:check && yarn deps:update
# convenience scripts.
# @link https://github.com/raineorshine/npm-check-updates
reject: [
    # Add here exclusions on packages if any
    "eslint",
    "i18next",
    "string-strip-html",
]
