defaultSemverRangePrefix: ""

enableGlobalCache: false

nmMode: hardlinks-local

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.1.0-rc.8.cjs

# Packages sometimes forget to list their dependencies.
# @link https://yarnpkg.com/getting-started/migration#fix-dependencies-with-packageextensions
packageExtensions:
  "apollo-server-micro@^3.3.0":
    peerDependencies:
      "graphql": "15.6.1"
  "@endemolshinegroup/cosmiconfig-typescript-loader@^3.0.2":
    peerDependencies:
      "typescript": "^4.4.2"