compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

nmMode: hardlinks-local

nodeLinker: node-modules

packageExtensions:
  "@endemolshinegroup/cosmiconfig-typescript-loader@^3.0.2":
    peerDependencies:
      typescript: ^4.4.2
  apollo-server-micro@^3.3.0:
    peerDependencies:
      graphql: 15.6.1

yarnPath: .yarn/releases/yarn-4.1.1.cjs
